NodeJS week3 HW
Hani-far/Meal-Sharing pull request #1
Opened 2021-05-14 09:12 UTC by Hani-far

2021-05-16 10:33 UTC, florinmaticu commented on src/backend/api/meals.js
> +    throw error;
you can return an response with error code 500 instead of throwing an exception. the current code would most likely crash since the exception is not caught and handled

2021-05-16 10:33 UTC, florinmaticu commented on src/backend/api/meals.js
> +      .where("id", mealId);
```suggestion
      .where("idmeals", mealId);
```
assuming that you generated the database from `database_dump_meals.sql` 

```
 `idmeals` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(45) DEFAULT NULL,
  `number_of_guests` int(11) DEFAULT NULL,
  PRIMARY KEY (`idmeals`)
```

2021-05-16 18:15 UTC, florinmaticu requested changes

2021-05-16 18:15 UTC, florinmaticu commented on src/backend/api/meals.js
> +      const limit = request.query.limit;
```suggestion
      const limit = Number(request.query.limit);
```

2021-05-16 18:55 UTC, Hani-far commented on src/backend/api/meals.js
> +      const limit = request.query.limit;
Thanks

2021-05-16 19:11 UTC, Hani-far commented on src/backend/api/meals.js
> +    throw error;
Thanks for your time and feedback

2021-05-17 05:55 UTC, florinmaticu approved these changes

2021-05-17 12:03 UTC, merged